report_type: jdbc
uri_suffix: accessions_ip_status
description: "Displays the intellectual property status of listed accession(s). Report contains accession number, linked resources, title, extent, cataloged, date processed, rights transferred and a count of the number of records selected with rights transferred."
