/*
 * A frame to perform basic searching
 */
package areports;

import java.sql.Connection;
import java.sql.SQLException;
import quick.dbtable.DBTable;

/**
 *
 * @author nathan
 */
public class SearchFrame extends javax.swing.JFrame {

    private DBTable dBTable;

    /**
     * Creates new form SearchFrame
     */
    public SearchFrame(Connection connection) {
        initComponents();
        addQuickTable(connection);
    }

    /**
     * Method to add the quicktable component
     */
    private void addQuickTable(Connection connection) {
        dBTable = new quick.dbtable.DBTable();

        //add to frame
        getContentPane().add(dBTable);

        dBTable.setConnection(connection);

        // set the select statement which should be used by the table
        String testSQL = "SELECT\n"
                + "     resource.`id` AS resourceId,\n"
                + "     resource.`repo_id` AS repo_id,\n"
                + "     resource.`title` AS title,\n"
                + "     resource.`identifier` AS resourceIdentifier,\n"
                + "     GetResourceCreator(resource.`id`) AS displayCreator,\n"
                + "     GetEnumValueUF(resource.`language_id`) AS languageCode,\n"
                + "     GetEnumValueUF(resource.`level_id`) AS level,\n"
                + "     GetResourceDateExpression(resource.`id`) AS dateExpression,\n"
                + "     GetResourceExtent(resource.`id`) AS extentNumber,\n"
                + "     GetResourceExtentType(resource.`id`) AS extentType,\n"
                + "     GetResourceContainerSummary(resource.`id`) As containerSummary,\n"
                + "     resource.`restrictions` AS restrictionsApply\n"
                + "FROM\n"
                + "     `resource` resource";
        dBTable.setSelectSql(testSQL);

        try {
            //fetch the data from database to fill the table
            dBTable.refresh();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Form");

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
